### ISSUE TITLE
[FR] CLI utils for temporary exemption and inclusion

### ISSUE THREAD

**Issue by PoneyClairDeLune** [black-desk/cgtproxy#205]
Just like `cgproxy` and `cgnoproxy`, a CLI utility for temporary exemption and inclusion would be incredibly useful.

**Comment by black-desk** [comment]
https://github.com/black-desk/cgtproxy/blob/8cfd5e3b19e959ada8d155c822c4d962cae78b7c/misc/config/example.yaml#L70-L73

**Comment by black-desk** [comment]
I will close this for now. If you has any other question about this trick, feel free to reopen this issue.
